### ISSUE TITLE
CLI outputs only `nextState.data` and not `nextState`

### ISSUE THREAD

**Issue by muhammad-levi** [OpenFn/kit#194]
### User story
Given an initial state,
When a job expression ran,
Then it should outputs next state.

### Details
When I tried to use OpenFn/CLI to test a job expression that is using adaptor PostgreSQL, the data from the SQL call is in the `state.response`, but because CLI outputs only `state.data`, the output.json file becomes like this:
```json
{
  "data": null
}
```

**Comment by josephjclark** [comment]
Hi, thanks for trying out the new CLI!

Try and add the `--no-strict-output` flag when you call `openfn` (ie, `openfn expression.js -a postgres --no-strict-output`). This will output all your state (except config if I recall correctly), not just state.data.

At the moment we're exploring being more strict with the output object and only serialising stuff you write to `state.data`. This is part of a wider process of re-thinking how state is used. But we haven't added any documentation around this yet so it's all a bit mysterious.

In the meantime we need to work out the best default for now and update our documentation accordingly.

**Comment by josephjclark** [comment]
We've updated documentation, which may help, so I'm closing this down for the time being.

I've made a mental note that strict output is going to be confusing for folks migrating from devtools. I'll keep an eye on this as we go forward.

Thanks again for reaching out @muhammad-levi! Really helpful!
