### ISSUE TITLE
Runtime: Jobs should receive the state of their upstream job (?)

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#227]
Here's an interesting one:

```
   a
 /   \
x     y

jobs: [
 { id: 'a', expression: '...', next: { x true, y: true },
 { id: 'x', expression: '...' }, 
 { id: 'y', expression: '...' }
]
```

In this workflow, `a` will generate some state and pass it down to `x` and `y`.

But what happens in the workflow right now is:
* Execute `a` with initial state `s`
* Save the state
* Execute `x` with the latest state (`s'1`)
* Save the state
* Execute `y` with  the latest state (`s'2'`)
 
There are a few consequences of this:

* If `x` returns no state, `y` will receive no state as input. This isn't unreasonable from `x`'s point of view as its a leaf node, it has no dependencies
* If `x` happens to overwrite or remove some state that `y` depends on, `y` will likely fail.

This means we stop thinking about a single state that is shared by every job to return a final answer, and start thinking of state as more isolated thing which is passed down various independent streams.

## Solution

The runtime needs to save the state produced by each job. When running each new job, it needs to look at the upstream job, find its state, and pass it in.

If there are multiple upstream jobs (not possible right now) the states must be merged.

## Final state

But what does this mean for the final state returned by the workflow? It has two end points, two results, two final states.

Is it an aggregation of all the state objects merged together? If there are conflicting keys, who wins? Should we deep merge nested objects? Nested arrays?

Is it just the thing returned by the last job?

Or do we return an index of the states returned by each job?

**Comment by josephjclark** [comment]
@taylordowns2000 I think this is correct (tl;dr - we should only pass the output of a job to its downstream jobs), can I get your input on it before I set about it?

I suggest we aggregate all "leaf" node states at the end and just return whatever it ends up looking like. If you have a branching flow like this, you probably don't care too much about your final state.

**Comment by taylordowns2000** [comment]
@josephjclark , yes on the first bit: we should only pass the output of a job to its downstream jobs to preserve [this contract](https://docs.openfn.org/documentation/jobs/state#states-by-job-trigger-type).

For final state of a workflow, i'd expect to see a single state object if there are no branches. if there are multiple branches, i _guess_ i'd expect to see an array of final state objects but (a) I'd probably be able to tell which came from which "job" just be looking and (b) no... i wouldn't care too much about final state.

re: (b), as a matter of fact, the reason I _used to_ care so much about final state is because i had to use it to build the input for a downstream job by hand... and we've already taken care of that!

**Comment by josephjclark** [comment]
Ok, I'll get on and ensure that state is passed downstream - that bit at least is esay.

It's clearly a bit complicated if there are multiple parallel jobs.

Perhaps:
a) If there's only one final state, well that's easy we just return it; 
b) If there are multiple states, we return an object with the final state for each "terminal"/leaf job.

```
// single  return
{ data: { ... }  }

// multiple returns
{ job3: { data: { ... }  }, job6: { data: { ... } } }
```
I don't really like that there are two very different structures though. Is there even any way to identify whether you've dealing with a single or multiple return? I suppose you can scan for a data key but yiish.

So what if we  introduce some sort of aggregation jnode which takes state from multiple jobs and merges them, either for a final downstream job or for state. Its input is a multiple-return indexed object. It's just a job with multiple inputs and no adaptor.. A "default" aggregator would just iterate and spread in basically a random order.

![image](https://user-images.githubusercontent.com/7052509/234652487-d3f51d13-d368-4a18-9258-30e51e1704a4.png)

If you have a default aggregator like that, and an easy way to define a final state aggregator, suddenly you never need to return final state.

I guess a job would define an "aggreagtor" or "input-merge" function, which sits alongside its expression, and is invoked whenever it has multiple inputs.

Complicated stuff. Will have to sleep on it.
