### ISSUE TITLE
Remove workflow box and update highest workflow box to include a name

### ISSUE THREAD

**Issue by amberrignell** [OpenFn/kit#24]
### User story
As a user that is looking at a workflow for the first time, I would like to easily identify the name of a workflow and understand when it gets triggered. 

### Details
remove the “workflow” wrapper node
change the “webhook” node to have the workflow name and describe how the workflow gets triggered. (make it bigger so that it is obviously different to the rest of the nodes in a workflow)

![workflow](https://user-images.githubusercontent.com/36554605/192232593-caadb90b-0a82-4caf-84ad-e9997f82c42e.png)

### Implementation notes

1. clone `OpenFn/kit`
2. read `README.md`
4. start the flow example with `pnpm run -C examples/flow start`
5. cd into `/packages/workflow-diagram` and start a build/watch with `pnpm run watch`
6. take a look at the example which is now running in your browser on http://127.0.0.1:8080/
7. take a look at how this example gets "fed" by a project description at `examples/flow/src/index.jsx`
8. head over to `packages/workflow-diagram/src/layout/index.ts` and see how the example gets built.
9. To start work, you _might_ approach this by removing the wrapper node entirely and _modifying_ the trigger node so that it displays information about both the workflow (name) and the trigger (details).

**Comment by josephjclark** [comment]
Should this be in the Lightning repo @amberrignell ?

**Comment by amberrignell** [comment]
Pretty sure this is kit - changes need to be made with how we show the workflow diagram (react-flow changes). Let's discuss in standup?

**Comment by josephjclark** [comment]
Oh I see, yes fair enough :)
