### ISSUE TITLE
End-users need log level control for `console.log` and `console.debug`

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/kit#276]
Currently, users are frequently adding and removing `console.log(state.patientInfo)` lines of code because they want to see them in their test projects, but are not allowed to show them in their production projects.

In v1, at the job level (controlled by Elixir, not Js) admins can actually enable/disable _ALL_ use of console.log.

This is a crude solution, as the way these jobs look often requires both... sorta like this:

```js
fn(state => {
  const { patients } = state;
  console.log('We will process', patients.length, 'patients right now.');
  console.debug('Only visible during low-security sandbox execution', patients);
  return state;
});
```

I'd like a CLI user, or Lightning, to be able to run this same job with two different log levels, one which displays _both_ the log and the `debug`, and the other than displays only the `log`.

Right now even log-level `none` displays the debugs. The log level settings seem to be more geared towards system-generated logs, rather than job-code generated logs. I think we need both.
<img width="551" alt="image" src="https://github.com/OpenFn/kit/assets/8732845/fa913da3-4ce7-4119-923a-d178c18c1029">

**Comment by josephjclark** [comment]
@taylordowns2000 First of all, I gotta flag that we're only talking about the CLI here. Logging rules for the RTM may be different (I'll get to that).

In the CLI, the job will by default run at `debug` level, on the assumption that if you've put a log statement in your job code you definitely want to see it in the output.

You need to explicitly set job level logging with `--log job=whatever`. This isn't a nice interface (there's an issue for it), i kinda wanted to assess its usage before making it super slick.

So if you do `openfn -l job=info etc..` do you get the output you expect?` 

I've opened #227 to track this CLI API quirk - it's clearly not right at the moment (even if it's doing what I think I originally wanted).

Secondly, I think the problem of preventing (not hiding) logging in production vs development is a different issue (literally, it's #182). We do need to provide some kind of `console.dev()` API which only logs in a dev environment (and somehow a flag gets passed to the runtime to indicate whether we're using dev or production credentials).

Finally, this may all feel a bit different with the RTM. The design at the moment is: the RTM will log EVERYTHING, post it to Lightning, and Lightning will filter the output to what the user wants to see.

But if we're logging sensitive data in production, we want to stop it logging, getting posted on the wire , AND getting saved to the database. We need a more drastic intervention there.

**Comment by taylordowns2000** [comment]
Super cool. OK, so:

1. Yes, `-l job=info` does exactly what I want. Thank you!
2. Makes sense, re: RTM, but that more drastic intervention does seem to be the thing we're looking for. I will post a comment on #182 with thoughts on the desired UX for the non-devs who most commonly handle this stuff and we can figure out the RTM/Lightning interaction from there
