### ISSUE TITLE
deploy: fails if state.json isn't present

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#357]
`openfn deploy` requires `project.yaml` and `state.json` to be present when it runs.

If there is no `state.json`, you get this error:

![image](https://github.com/OpenFn/kit/assets/7052509/2a25a758-27ed-47de-836c-ef0ee31c6d19)

If there is a state.json the deploy will succeed (fun fact: state.json can contain anything - json, yaml, javascript, ascii, the complete works of shakespearses - and `deploy` will handle it. It just freaks out if it can't find the file at all.

I don't _think_ we need state.json to exist on the first sync, so we should be able to survive this. But we should also throw appropriate errors. If state.json exists and doesn't contain valid project state, we should error.

**Comment by taylordowns2000** [comment]
@josephjclark , thanks for picking this up. i've updated the original specification for deploy here (calling the thing that gets created or updated after each deploy `state.json` to align with what's actually been built) and popped it below for whoever picks up this issue
<img width="1260" alt="image" src="https://github.com/OpenFn/kit/assets/8732845/75a609eb-ea1b-4b16-b726-eb1dd26158d2">
