### ISSUE TITLE
CLI: ReferenceError: dateFns is not defined

### ISSUE THREAD

**Issue by mtuchi** [OpenFn/kit#363]
### User story
When using `http` adaptor, The jobs that are using `common/src/dateFns.js` or `common/src/http.js` fails with reference-error:
```
[R/T] ✘ Failed job fetch-gc-submissions after 2.664s
[R/T] ✘ ReferenceError: dateFns is not defined
[R/T] ✘ Check state.errors.fetch-gc-submissions for details.
```
The version of CLI kit that i am using 
```
[CLI] ℹ Versions:
         ▸ node.js     18.12.1
         ▸ cli         0.2.4
         ▸ runtime     0.0.28
         ▸ compiler    0.0.34
```

**Comment by josephjclark** [comment]
Adaptor docs is actually a bit broken too, as it lists the http functions of common at the root.

![image](https://github.com/OpenFn/kit/assets/7052509/2a671fc2-7240-4043-b97c-0dd769c0d6f9)

I sort of remember doing that - unsure if I misunderstood the structure of the package or if it was a deliberate workaround
