### ISSUE TITLE
RTM Server: update how the Attempt is assembled

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#367]
We need to break down the Attempt creation flow.

Instead of fetching everything right from the queue, we need to make several requests:

- First we get the Attempt ID from the queue
- Then we get the actual Attempt JSON (execution plan)
- Then we get the state (Input Dataclip ID)
- When each Job starts, load the credential if needed

Note: use lazy objects with async getter properties which can lazy load data from Lightning on demand (with cache and fetch pooling)

**Comment by NickOpenFn** [comment]
Might be done
