### ISSUE TITLE
RTM Server: handshake with Lightning (Worker Token)

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#369]
The RTM server, on startup, needs to handshake with Lightning.

* Generate a JWT based on the shared secret token (Lightning has the same token)
* Send the JWT up to lightning (WHAT ENDPOINT?)
* Lightning will acknowledge the JWT

Lightning should reject ALL RTMS requests which do not have a valid JWT.

**Comment by josephjclark** [comment]
@stuartc I think the Worker Token here should be verified, using the shared secret.

Any feelings on what the payload should be? I guess some kind of unique identifier for the server, so that lightning can associate a JWT with a particular server. I don't really want to use a UUID for this as jwts should be compact. Maybe a [human-id](https://www.npmjs.com/package/human-id) (such as used by changesets)

**Comment by stuartc** [comment]
@josephjclark yeah I think that human-id is a great addition to the issuer text (version @ host), a new human-id every time it starts

**Comment by josephjclark** [comment]
Closing. Taking a wild guess at the effort here to be 5 points. Very hard to say
