### ISSUE TITLE
Exit Reasons

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#396]
When a job finishes, the worker needs to include an exit status, reason and message in the event.

Here's an attempt at capturing the reasons

| Priority | Status  | Exit Reason    | Exit Message                 |                                                                  |
|----------|---------|----------------|------------------------------|------------------------------------------------------------------|
| 0        | Planned | -              | -                            | job pending                                                      |
| 1        | success | OK              | -                            | completed without throwing                                       |
| 2        | fail    |               | -                            | completed but threw an error (error on state)                    |
|          |         | RUNTIME_ERROR  | state is not defined         | Some kind of js runtime exception (likely a reference error)     |
|          |         | ERROR          | Patient not found, http 500? | Error thrown by a user or adaptor (ie throw new Error('abort!')) |
|          |         | IMPORT_ERROR   |                              | failed to import a dependency (likely an adaptor problem)        |
|          |         | SECURITY_ERROR | code generation disabled     | User tried to execute code that we deem insecure                 |
| 3        | crash   |               | -                            | Job did not execute or return                                    |
|          |         | OOM            |                              | Out of memory error occured on the job                           |
|          |         | TIMEOUT        |                              | Timeout occured from the job                                     |
|          |         | COMPILE_ERROR  |                              | Failed to compile the job code, likely a syntax error            |
|          |         | CRASH  |                              | Stand-in for some kind of crash without a known reason           |

Table generated from: https://www.tablesgenerator.com/markdown_tables

Other errors: DISK_SPACE

The reason should be a short-ish list of enums (Lightning will go on to classify the exist reason into a status to report to the user). The message, which is optional, adds context and detail and may be displayed to the user.

The attempt will also have an exit status and reason. Right now, this will be the highest priority status/reason found across the workflow. But I think we'll need to look at that later because a user-handled, expected error may skew the result.

This is ostensibly a worker issue but it is likely to have knock-on work in the engine and maybe even runtime

Related is https://github.com/OpenFn/kit/issues/394 - I think we can plug in a reasons framework first, and then work #394 into it after.

**Comment by stuartc** [comment]
This looks good @josephjclark, might I suggest a "NORMAL" or "OK" in the case of a successful exit? It makes things easier on the lightning side to have a concrete value for giving a green tick etc.

**Comment by josephjclark** [comment]
I don't think the table above is quite right, it's a bit hard to map the reasons to priorities (or statuses). It's also a little inflexible.

What if every attempt complete returns `{ exit_status, exit_reason, exit_message }` (note that if the attempt crashes, it'll still return an attempt complete event (if it can, otherwise lightning has to time it out))

| priority | status | reason               | message                               | Comment                                                                   |
| -------- | ------ | -------------------- | ------------------------------------- | ------------------------------------------------------------------------- |
| 1        | OK     | .                   | .                                    | Attempt completed without errors                                          |
| 2        | Fail   | RUNTIME_ERROR        | ReferenceError: state is not defined  | The attemped completed normally but threw one or more errors              |
|          |        | IMPORT_ERROR         | Failed to load adaptor: common@1.0.0  | Any issue loading dependencies through the linker (may not be an adaptor) |
|          |        | SECURITY_ERROR       | Eval is disabled for this context     | Any security malpractice we may catch. Perhaps this is acrash?            |
|          |        | ERROR                |                                       | General error                                                             |
|          |        | ...                  |                                       | We can freely support other error reasons                                 |
| 3        | Crash  | DATACLIP_LOAD_FAIL   | Failed to load dataclip 'xyz'         | Failed to load the initial dataclip for some reason.                      |
|          |        | CREDENTIAL_LOAD_FAIL | Failed to load credential 'abc'       | Failed to load a credential for some reason                               |
|          |        | OOM                  | Job exeeded memory threshold of 500mb |                                                                           |
|          |        | TIMEOUT              | Job exceeded thet timeout of 5000ms   |                                                                           |
|          |        | COMPILER_ERROR       | Unexpected token '@' at line 1, col 1 |                                                                           |
|          |        | CRASH                |                                       | General catch off for unexpected errors (ie if the runtime throws)        |

A fail means the attempt completed normally in the runtime, but may have one or more errors on state. But it does return a state object.

A crash means the attempt failed to execute

In this approach we could encode status as a number, 1 2 or 3. Reason and message are strings. Reason would be a finite list which could slowly expand over time.

**Comment by josephjclark** [comment]
Thinking about a simpler ?() alternative. For a Fail state, we send a message to attempt:complete with errors. For a crash state, we message attempt:error.

So rather than returning to the same endpoint with different "error codes", we return to different endpoints.

attempt:complete means  "I ran the job and it's all fine but there may have been some errors raised along the way, which the user should take a look at"

attempt:error means "I failed to execute this workflow and have aborted early for some very good reason"

**Comment by josephjclark** [comment]
I'm also starting to wonder again about the crash/fail distinction. Why should OOM be more critical than IMPORT_ERROR? Or RUNTIME_ERROR?

Maybe I've just  got the distinction wrong here. These are all "failed to execute" errors rather than user or adaptor thrown errors. Maybe even that doesn't work - what happens when Salesforce throws a 401 or http throws a 500?

Some crash states here are user error (like syntax error from the compiler) and require user attention (probably oom too). And some fail states, like "sorry I failed to load this adaptor", are probably system/admin issues and are bugs, rather than user error.

Also a bit worried that "crash doesn't return state" thing isn't right. If job A ran but job B timed out, we probably want to inspect the state of job a so that we can re-run or try to reproduce locally.

**Comment by josephjclark** [comment]
I think this is where we've landed on the statuses:

| reason    | summary                                                                        | example                                                    |
|-----------|--------------------------------------------------------------------------------|------------------------------------------------------------|
| ok        | no errors at all                                                               |                                                            |
| cancelled | user killed the job for some reason                                            | user aborted the job in lightning                          |
| fail      | Error came out of the job but we continued execution as much as we could       | http threw a 500 code; user threw their own Error          |
| crash     | Something went severely wrong and the engine or worker aborted exeuction early | error loading credentials, runtime exception, syntax error |
| killed    | Something happned we didn't like and we killed/aborted the workfllow early     | security error, admin shut down server, timeout, oom       |
| lost      | Lightning struck off the attempt because it didn't complete in time            | Probably means the worker lost conection to lightning      |

In addition:

* We send errors with `{ reason }` to `run:complete`
* There will always be a human-readable message
* I will include a `{ source }` key, ie, compiler, runtime, engine, worker
* Attempt reasons we'll work out later - this is RUN reasons

**Comment by josephjclark** [comment]
Taylor wants the attempt reason to be calculated in the worker

**Comment by josephjclark** [comment]
Final spec for run complete payloads (in pseudo typescript):
```
reason: 'ok' | 'cancelled' | 'failed' | 'killed' | 'crashed' (I don't send 'lost', lightning must infer it)
message?: string // human readable, user-friendly, english language string
error_type?: string // a finite (but growing) list of known errors, ie, ReferenceError, AdaptorError, OOMError
source?: what component (runtime, worker, engine, compiler) reported the error
```

Questions / comments
* Are reasons past tense (cancelled) or present (cancel) ?
* `ok` or `success`?
* I don't like `error_type`, but `type` is too vague. Maybe `error: ReferenceError` is ok?

I am pretty sure that the attempt:complete payload will be exactly the same, but may want to include a run id (ie, the run the fail state came from)

**Comment by taylordowns2000** [comment]
@josephjclark , let's chat about this on Monday—we are getting the `run:complete` event on Lightning when a run is successful, but not when it's got a good error. here are the lightning logs (with ws-worker inline)

job one "good" succeeds. job two "bad" fails.

<img width="1263" alt="image" src="https://github.com/OpenFn/kit/assets/8732845/d6275bc9-3549-418e-aa64-9b6faa9dbc36">


```[info] [SRV] ℹ 02bcee87-fa8d-4dae-bc6a-b1c7538c237a :: attempt:start :: OK
[debug] QUERY OK db=0.2ms idle=295.1ms
begin []
[debug] QUERY OK source="attempts" db=27.3ms
WITH "subset" AS (SELECT sa0."id" AS "id" FROM "attempts" AS sa0 WHERE (sa0."state" = 'available') ORDER BY sa0."priority", sa0."inserted_at" LIMIT $1 FOR UPDATE SKIP LOCKED) UPDATE "attempts" AS a0 SET "state" = $2, "claimed_at" = $3 FROM "subset" AS f1 WHERE (a0."id" = f1."id") RETURNING a0."id", a0."work_order_id", a0."reason_id", a0."starting_job_id", a0."starting_trigger_id", a0."created_by_id", a0."dataclip_id", a0."state", a0."claimed_at", a0."started_at", a0."finished_at", a0."priority", a0."inserted_at" [1, :claimed, ~U[2023-11-05 12:23:39.897828Z]]
[debug] QUERY OK db=0.5ms
commit []
[debug] HANDLED claim INCOMING ON worker:queue (LightningWeb.WorkerChannel) in 29ms
  Parameters: %{"demand" => 1}
[debug] QUERY OK db=102.7ms idle=467.8ms
begin []
[debug] QUERY OK source="attempts" db=12.5ms
WITH "subset" AS (SELECT sa0."id" AS "id" FROM "attempts" AS sa0 WHERE (sa0."state" = 'available') ORDER BY sa0."priority", sa0."inserted_at" LIMIT $1 FOR UPDATE SKIP LOCKED) UPDATE "attempts" AS a0 SET "state" = $2, "claimed_at" = $3 FROM "subset" AS f1 WHERE (a0."id" = f1."id") RETURNING a0."id", a0."work_order_id", a0."reason_id", a0."starting_job_id", a0."starting_trigger_id", a0."created_by_id", a0."dataclip_id", a0."state", a0."claimed_at", a0."started_at", a0."finished_at", a0."priority", a0."inserted_at" [1, :claimed, ~U[2023-11-05 12:23:40.071740Z]]
[info] [R/T] ❯ Executing expression (1 operations)
[info] [R/T] ❯ Starting operation 1
[info] [R/T] ℹ Operation 1 complete in 0ms
[info] [R/T] ❯ Expression complete!
[info] [R/T] ❯ {
[info]   "configuration": {},
[info]   "data": {}
[info] }
[info] [R/T] ✔ Completed job f2367ddd-ab0d-4a2d-9a6a-51eb91f3313c in 352ms
[info] [R/T] ♦ Starting job 7ea4acab-96f4-4b32-bc2f-896ee4a961e3
[info] [R/T] ❯ Intialising pipeline
[info] [R/T] ❯ Timeout set to 300000ms
[info] [R/T] ❯ [linker] loading module @openfn/language-http
[info] [R/T] ❯ [linker] Loading module @openfn/language-http from /tmp/openfn/repo/node_modules/@openfn/language-http_latest/dist/index.cjs
[info] [R/T] ℹ Resolved adaptor @openfn/language-http to version 5.0.4
[debug] QUERY OK db=70.2ms
commit []
[debug] HANDLED claim INCOMING ON worker:queue (LightningWeb.WorkerChannel) in 187ms
  Parameters: %{"demand" => 1}
[debug] QUERY OK source="attempts" db=20.0ms idle=635.6ms
SELECT a0."id", j2."id" FROM "attempts" AS a0 LEFT OUTER JOIN "work_orders" AS w3 ON a0."work_order_id" = w3."id" LEFT OUTER JOIN "workflows" AS w1 ON w3."workflow_id" = w1."id" LEFT OUTER JOIN "jobs" AS j2 ON (j2."workflow_id" = w1."id") AND (j2."id" = $1) WHERE (a0."id" = $2) ["f2367ddd-ab0d-4a2d-9a6a-51eb91f3313c", "02bcee87-fa8d-4dae-bc6a-b1c7538c237a"]
[debug] QUERY OK db=0.2ms idle=654.7ms
begin []
[debug] QUERY OK db=0.5ms
INSERT INTO "runs" ("id","started_at","job_id","input_dataclip_id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6) ["82301f39-c9e4-4204-aa52-adb377b12bcc", ~U[2023-11-05 12:23:40.241260Z], "f2367ddd-ab0d-4a2d-9a6a-51eb91f3313c", "0e189878-95b3-4ec1-b294-0a7f36feb9c8", ~U[2023-11-05 12:23:40.262098Z], ~U[2023-11-05 12:23:40.262098Z]]
[debug] QUERY OK db=0.2ms
INSERT INTO "attempt_runs" ("id","run_id","attempt_id","inserted_at") VALUES ($1,$2,$3,$4) ["ae5a8af1-1ffc-4c44-86b8-a4384b62efa1", "82301f39-c9e4-4204-aa52-adb377b12bcc", "02bcee87-fa8d-4dae-bc6a-b1c7538c237a", ~U[2023-11-05 12:23:40.262786Z]]
run complete payload: %{
  "job_id" => "f2367ddd-ab0d-4a2d-9a6a-51eb91f3313c",
  "output_dataclip" => "{\"configuration\":{},\"data\":{}}",
  "output_dataclip_id" => "282edadf-9789-4e99-9853-c4c45812257a",
  "reason" => "success",
  "run_id" => "82301f39-c9e4-4204-aa52-adb377b12bcc"
}
[debug] QUERY OK db=0.3ms
commit []
[debug] HANDLED run:start INCOMING ON attempt:02bcee87-fa8d-4dae-bc6a-b1c7538c237a (LightningWeb.AttemptChannel) in 22ms
  Parameters: %{"input_dataclip_id" => "0e189878-95b3-4ec1-b294-0a7f36feb9c8", "job_id" => "f2367ddd-ab0d-4a2d-9a6a-51eb91f3313c", "run_id" => "82301f39-c9e4-4204-aa52-adb377b12bcc"}
[info] [SRV] ℹ 02bcee87-fa8d-4dae-bc6a-b1c7538c237a :: run:start :: OK
[debug] QUERY OK db=0.1ms idle=654.2ms
begin []
[debug] QUERY OK source="runs" db=0.1ms
SELECT r0."id", r0."exit_code", r0."exit_reason", r0."finished_at", r0."started_at", r0."job_id", r0."credential_id", r0."input_dataclip_id", r0."output_dataclip_id", r0."previous_id", r0."inserted_at", r0."updated_at" FROM "runs" AS r0 WHERE (r0."id" = $1) ["82301f39-c9e4-4204-aa52-adb377b12bcc"]
[debug] QUERY OK db=0.3ms
INSERT INTO "dataclips" ("id","type","body","project_id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6) ["282edadf-9789-4e99-9853-c4c45812257a", :run_result, %{"configuration" => %{}, "data" => %{}}, "4adf2644-ed4e-4f97-a24c-ab35b3cb1efa", ~U[2023-11-05 12:23:40.264386Z], ~U[2023-11-05 12:23:40.264386Z]]
[debug] QUERY OK db=0.2ms
UPDATE "runs" SET "exit_reason" = $1, "finished_at" = $2, "output_dataclip_id" = $3, "updated_at" = $4 WHERE "id" = $5 ["success", ~U[2023-11-05 12:23:40.265068Z], "282edadf-9789-4e99-9853-c4c45812257a", ~U[2023-11-05 12:23:40.265082Z], "82301f39-c9e4-4204-aa52-adb377b12bcc"]
[debug] QUERY OK db=0.1ms
commit []
[debug] HANDLED run:complete INCOMING ON attempt:02bcee87-fa8d-4dae-bc6a-b1c7538c237a (LightningWeb.AttemptChannel) in 2ms
  Parameters: %{"job_id" => "f2367ddd-ab0d-4a2d-9a6a-51eb91f3313c", "output_dataclip" => "{\"configuration\":{},\"data\":{}}", "output_dataclip_id" => "282edadf-9789-4e99-9853-c4c45812257a", "reason" => "success", "run_id" => "82301f39-c9e4-4204-aa52-adb377b12bcc"}
[info] [SRV] ℹ 02bcee87-fa8d-4dae-bc6a-b1c7538c237a :: run:complete :: OK
[info] [R/T] ❯ Executing expression (1 operations)
[info] [R/T] ❯ Starting operation 1
[debug] QUERY OK db=1.1ms idle=794.2ms
begin []
[debug] QUERY OK source="attempts" db=0.4ms
WITH "subset" AS (SELECT sa0."id" AS "id" FROM "attempts" AS sa0 WHERE (sa0."state" = 'available') ORDER BY sa0."priority", sa0."inserted_at" LIMIT $1 FOR UPDATE SKIP LOCKED) UPDATE "attempts" AS a0 SET "state" = $2, "claimed_at" = $3 FROM "subset" AS f1 WHERE (a0."id" = f1."id") RETURNING a0."id", a0."work_order_id", a0."reason_id", a0."starting_job_id", a0."starting_trigger_id", a0."created_by_id", a0."dataclip_id", a0."state", a0."claimed_at", a0."started_at", a0."finished_at", a0."priority", a0."inserted_at" [1, :claimed, ~U[2023-11-05 12:23:40.432723Z]]
[debug] QUERY OK db=0.1ms
commit []
[debug] HANDLED claim INCOMING ON worker:queue (LightningWeb.WorkerChannel) in 2ms
  Parameters: %{"demand" => 1}
[debug] QUERY OK source="attempts" db=51.1ms idle=756.5ms
SELECT a0."id", j2."id" FROM "attempts" AS a0 LEFT OUTER JOIN "work_orders" AS w3 ON a0."work_order_id" = w3."id" LEFT OUTER JOIN "workflows" AS w1 ON w3."workflow_id" = w1."id" LEFT OUTER JOIN "jobs" AS j2 ON (j2."workflow_id" = w1."id") AND (j2."id" = $1) WHERE (a0."id" = $2) ["7ea4acab-96f4-4b32-bc2f-896ee4a961e3", "02bcee87-fa8d-4dae-bc6a-b1c7538c237a"]
[debug] QUERY OK db=0.2ms idle=669.1ms
begin []
[debug] QUERY OK db=1.0ms
INSERT INTO "runs" ("id","started_at","job_id","input_dataclip_id","inserted_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6) ["4dc2a437-d345-444a-b0ba-9aee0f9598d0", ~U[2023-11-05 12:23:40.390503Z], "7ea4acab-96f4-4b32-bc2f-896ee4a961e3", "282edadf-9789-4e99-9853-c4c45812257a", ~U[2023-11-05 12:23:40.442339Z], ~U[2023-11-05 12:23:40.442339Z]]
[debug] QUERY OK db=0.3ms
INSERT INTO "attempt_runs" ("id","run_id","attempt_id","inserted_at") VALUES ($1,$2,$3,$4) ["88cb5f2a-095c-4d63-aea4-c7f737438d3b", "4dc2a437-d345-444a-b0ba-9aee0f9598d0", "02bcee87-fa8d-4dae-bc6a-b1c7538c237a", ~U[2023-11-05 12:23:40.443758Z]]
[debug] QUERY OK db=0.2ms
commit []
[debug] HANDLED run:start INCOMING ON attempt:02bcee87-fa8d-4dae-bc6a-b1c7538c237a (LightningWeb.AttemptChannel) in 54ms
  Parameters: %{"input_dataclip_id" => "282edadf-9789-4e99-9853-c4c45812257a", "job_id" => "7ea4acab-96f4-4b32-bc2f-896ee4a961e3", "run_id" => "4dc2a437-d345-444a-b0ba-9aee0f9598d0"}
[info] [SRV] ℹ 02bcee87-fa8d-4dae-bc6a-b1c7538c237a :: run:start :: OK
[info] [R/T] ✘ Failed job 7ea4acab-96f4-4b32-bc2f-896ee4a961e3 after 251ms
[info] [R/T] ✘ ERR_BAD_REQUEST: Request failed with status code 405
[info] [R/T] ❯ {
[info]   "message": "Request failed with status code 405",
[info]   "name": "AxiosError",
[info]   "stack": "AxiosError: Request failed with status code 405\n    at settle (/private/tmp/openfn/repo/node_modules/axios/dist/node/axios.cjs:1268:12)\n    at IncomingMessage.handleStreamEnd (/private/tmp/openfn/repo/node_modules/axios/dist/node/axios.cjs:2446:11)\n    at IncomingMessage.emit (node:events:527:35)\n    at endReadableNT (node:internal/streams/readable:1589:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
[info]   "config": {
[info]     "transitional": {
[info]       "silentJSONParsing": true,
[info]       "forcedJSONParsing": true,
[info]       "clarifyTimeoutError": false
[info]     },
[info]     "transformRequest": [
[info]       null
[info]     ],
[info]     "transformResponse": [
[info]       null
[info]     ],
[info]     "timeout": 0,
[info]     "xsrfCookieName": "XSRF-TOKEN",
[info]     "xsrfHeaderName": "X-XSRF-TOKEN",
[info]     "maxContentLength": -1,
[info]     "maxBodyLength": -1,
[info]     "env": {},
[info]     "headers": {
[info]       "Accept": "application/json, text/plain, */*",
[info]       "Content-Type": "application/x-www-form-urlencoded",
[info]       "cookie": "",
[info]       "User-Agent": "axios/1.1.3",
[info]       "Accept-Encoding": "gzip, deflate, br"
[info]     },
iex(2)> DOMException [DataCloneError]: function httpAdapter(config) {
                                                                       return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise)...<omitted>...
                                                                                                                                                                   } could not be cloned.
                         at new DOMException (node:internal/per_context/domexception:53:5)
                                                                                              at worker.emit (/Users/taylor/build/Lightning/assets/node_modules/workerpool/src/worker.js:252:12)
                                at Object.workerEmit (/Users/taylor/build/Lightning/assets/node_modules/workerpool/src/index.js:31:10)
                                                                                                                                          at publish (file:///Users/taylor/build/Lightning/assets/node_modules/@openfn/engine-multi/dist/worker/worker.js:49:14)
                                                                                                at helper (file:///Users/taylor/build/Lightning/assets/node_modules/@openfn/engine-multi/dist/worker/worker.js:60:5)
                                                    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                                                                                                         [info]     "method": "post",
[info]     "responseType": "json",
[info]     "maxRedirects": 5,
[info]     "url": "https://docs.openfn.org/this-wont-work",
[info]     "params": {},
[info]     "data": null
[info]   },
[info]   "code": "ERR_BAD_REQUEST",
[info]   "status": 405
[info] }
[info] [R/T] ✘ Check state.errors.7ea4acab-96f4-4b32-bc2f-896ee4a961e3 for details.
[info] [RTE] ❯ Purging workers
```

I think this will best be solved with a pairing session. I'll run lightning and start the worker with a watch, you liveShare into the worker and we run through a few scenarios.

**Comment by josephjclark** [comment]
A change!! `ok` -> `success`

**Comment by josephjclark** [comment]
Not handling every case yet but I am tracking the most critical and the design is fundamentally done.
