### ISSUE TITLE
ws-worker: allow to launch prod build from js

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#421]
`ws-worker`'s `npm start` uses `ts-node-esm` and builds from source.

For prod environments, we should be running a pre-build js file.

This issue is to:
1) Make sure there's a build available in dist
2) Have npm start use the main build
3) Add a dev start command to run straight from source

**Comment by taylordowns2000** [comment]
noting that the "optimize for prod" step here https://github.com/OpenFn/kit/issues/418 will wait on this
