### ISSUE TITLE
Worker: respond 200 to ping/get

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#443]
Be polite and respond with a 200 to get requests at root

**Comment by taylordowns2000** [comment]
Love it. Can we ensure that it's health-check compatible from the get go?

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

https://komodor.com/blog/kubernetes-health-checks-everything-you-need-to-know/

**Comment by josephjclark** [comment]
Yep. It's in the short term backlog- shouldn't be too much effort
