### ISSUE TITLE
Worker autoinstall breaks if adaptor versions are not explicit

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#462]
If you run an attempt right now with an adaptor with no version, ie, `"@openfn/language-http"`, the worker will blowup horribly.

I think it'll autoinstall @latest, but when it comes to actually loading the adaptor, it won't find a matching version, and then throw.

Also, importantly, the error reporting in this case is _TERRIBLE_. It's actually mapping to a user error and failing (if it isn't killing the whole worker, that is)

**Comment by taylordowns2000** [comment]
@josephjclark , this relates to https://github.com/OpenFn/Lightning/issues/1369

**Comment by josephjclark** [comment]
@taylordowns2000 this should be double-buffered.

I totally agree that Lightning should be sending on fully-resolved adaptor name.

The worker EITHER needs to reject attempts without a fully resolved adaptor name, OR work out `@latest` by itself. I'm pretty sure I have code for doing that (the CLI does it and I'm re-using that code) so it's not much effect to add tolerance to the worker.

I can log a warning if an implicit version number does get through
