### ISSUE TITLE
Worker: credentials are being parsed wrongly

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/kit#465]
@josephjclark and @stuartc , heads up that we still might not have nailed down the credential/configuration passing stuff perfectly:

For this one, the config is a standard dhi2 "play server" credential:
```js
{
  username: "admin",
  password: "district",
  hostUrl: "https://play.dhis2.org/dev"
}
```

and the job uses dhis2 v4.03 with the expression:
```js
get('trackedEntityInstances/PQfMcpmXeFE');
```

It fails with:
```
[R/T] ❯ Executing expression (1 operations)
DEPRECATION WARNING: Please migrate instance address from `apiUrl` to `hostUrl`.
[R/T] ❯ Starting operation 1
Preparing get operation...
[SRV] ℹ 697bd168-507e-4b36-8fb2-fbcdfa755bb1 :: attempt:log :: OK
Using latest available version of the DHIS2 api on this server.
Sending get request to undefined/api/trackedEntityInstances/PQfMcpmXeFE
 with params: {}
connect ECONNREFUSED ::1:80
[R/T] ✘ Failed job 5074946c-9cb8-4778-88b8-751eb171a33c after 227ms
[R/T] ✘ UserError: connect ECONNREFUSED ::1:80
[R/T] ❯ {
  "source": "runtime",
  "includeStackTrace": false,
  "type": "UserError",
  "name": "UserError",
  "severity": "fail",
  "message": "connect ECONNREFUSED ::1:80"
}
```
and the thing that makes me think this is a config setup issue is that `Sending get request to undefined/api/...` bit. Also strange that it thinks we're missing `hostUrl` --- see the deprecation warning above.

Maybe a problem with credential loading/handoff between lightning and the worker?

**Comment by josephjclark** [comment]
I've run a test locally and this seems to be OK. If I DON'T send config then I get the same error as you - which suggest that it is indeed config not getting feed through.

**Comment by josephjclark** [comment]
This comes out as a UserError but it should really be an adaptorerror! I need to update my heuristic and check this.

**Comment by josephjclark** [comment]
Looking at the logs I can confirm that Lightning IS sending me a credential ID, but somehow it is not coming up on my converted plan

**Comment by josephjclark** [comment]
Got it: Lightning sends `credential_id`, but I am looking for `credential`
