### ISSUE TITLE
Calculate attempt state only from leaf nodes

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/kit#468]
@jyeshe just pointed out that the `exit_reason` being sent back from `ws-worker@v0.2.1` seems to be taking into consideration _non_ leaf nodes from the attempt.

<img width="1135" alt="image" src="https://github.com/OpenFn/kit/assets/8732845/ff9977e8-1be2-43f2-b1bf-b0d7caa2bf17">

<img width="936" alt="image" src="https://github.com/OpenFn/kit/assets/8732845/fb917bfe-5b50-46fb-a604-e210030b4670">

In the above attempt, the only leaf node which is reached is the "Notify CHW upload failed" node. The exit_reason there is `success`, so the `attempt:complete` message should have `{ reason: success, errorType: null, errorMessage: null }`.

When there are multiple leaf nodes in a graph, the worker should send the highest priority reason across all leaf nodes.

**Comment by taylordowns2000** [comment]
this may be solved in #455 - @josephjclark , let me know if you need details but this one is actually high priority

**Comment by josephjclark** [comment]
This isn't what we designed and agreed for exit reasons so it's not a "bug" and not on my radar.

But it's a great idea and definite improvement. I'll add it to the workload for this week.
