### ISSUE TITLE
Parallel state problems? (how is input_dataclip_id set?)

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/kit#479]
For workflows with parallel paths (like the image here)
<img width="400" alt="image" src="https://github.com/OpenFn/kit/assets/8732845/3f4a7f1f-abc7-4bbe-a171-fdeb54009158">

1. we are seeing the tope `validate form type` get executed
2. and then pass its state to _only_ the dhis2 job
3. and then the dhis2 job passes its state to the fhir job! (we'd expect it to get a copy of the final state from job 1)

it's almost as if the worker isn't handling the branching logic with state handling the way the CLI did. the order of these operations doesn't matter, but the "path" that a particular copy of state takes (when it forks and becomes 2 units of state moving through the tree) is key 

## test case to reproduce

- use language common for all
- job1:
  ```js
  fn(state => {
    state.thing = "1st job"
    return state;
  })
  ```
- job2 (on success of job1)
  ```js
  fn(state => {
    console.log('initial state', state)
    state.patha = 'path a doing cool things'
    return state;
  })
  ```
- job3 (on success of job 1)
  ```js
  fn(state => {
    console.log('initial state', state)
    state.pathb = 'path b wuz here'
    return state;
  })
  ```

The closer I look at this the more it seems like the way that input_dataclip_id gets reported to lightning may be the problem, not the execution state for the job itself in the runtime.

**Comment by taylordowns2000** [comment]
eish... no, i think this might be a problem with how lightning displays "input state" for a given run.

@stuartc , @josephjclark , how does `input_dataclip_id` get set for runs now?

**Comment by josephjclark** [comment]
Input_dataclip_id only affects the first job - after that it's all handled internal to the engine, and should really be the same as the cli.

I'll investigate in the morning 🫡

**Comment by josephjclark** [comment]
I wasn't sure for a while but I see what's happening!

When the worker published `run:start`, it is _extremely_ naive in how it works out the `input_dataclip_id` and is sending back the wrong value.

The runtime is handling parallelisation perfectly (I've just added more tests to prove that) - but the event coming out of the worker is incorrect.

**Comment by josephjclark** [comment]
Right so I think the solution here is:
* The runtime should publish the downstream and upstream jobs with job-start and job-complete events. So listeners will know where we're going and where we've been.
* The worker can use that information to attach the right dataclip id
