### ISSUE TITLE
Auto-install of adaptors (and other dependencies)

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#48]
A major design issue.

In the distant future, I want uncompiled jobs to look like this:

```
import { fn }  from '@openfn/language-common@^2.0.1'
import { each } from 'lodash@2'

fn(() => {...};
```
This enables us to a) version lock a job's dependencies and b) import arbitrary npm modules.

Couple of quick caveats here:
* It's up to the runtime manager whether and how to allow arbitrary module imports (i think the manager should have a whitelist of allowed modules). The principle in the runtime is simply that modules can be imported
* I expect the Lightning UI to do some heavy lifting when it comes to declaring imports
* We can of course still run a job from live JS or with no imports, in which case all this stuff is simply ignored.

The code above should compile into something like this, with a manifest declared as a set of directives at the top of the file:
```
'use @openfn/language-common 2.0.1';
'use lodash 2';

import { fn }  from '@openfn/language-common';
import { each } from 'lodash';

export default [fn(() => {...}];
```
The directives tell the runtime (or runtime manager maybe) what versions of dependencies to use.

Note that the compiler can auto-generate directives (at least for adaptors and maybe more) if certain options are passed (like how we generate imports for adaptors now).

## Auto Installing Dependencies

Somewhere in the new runtime stack, we'll need the ability to auto-install a language adaptor (and eventually any arbitrary npm module).

This is either the job of the runtime manager or the runtime itself. At the time of writing I actually think it's for the runtime.

### Runtime Manager

The most obvious approach in this architecture is that the runtime manager ensures dependencies are installed and available to the runtime before anything runs. The manager should pass paths to each import to the runtime, which the linker will resolve at runtime. There is already a mechanism for this in place.

A major disadvantage of this approach is that the work needs to be duplicated across different managers. Specifically the CLI and the web service would both need a solution to the same problem - downloading and installing modules. This may mean implementing the installer as an export of the runtime, or as its own package in the monorepo (neither of which really appeals in this architecture!).

### Runtime

Alternatively we can push this logic directly down into the runtime.

This makes sense because it's the runtime's linker which has to resolve modules anyway - why shouldn't the linker be able to install modules on the fly, manage its own cache, etc?

The runtime would have to do the following:
* Read the manifiest at the top of the job source
* Run a setup step before executing the pipeline and install any modules into a specific folder (which it can log and report events for)
* Run the job and have the linker resolve modules on demand

The runtime would need some kind of working directory to save all its node modules in, and would presumably need an API to purge this directory somehow to prevent disk space exploding. This bit feels like a runtime manager problem -  I guess the runtime manager tells the runtime its working dir and when and how to purge it.

## Loading Mechanisms

Regardless of WHO does the loading, down at the metal, we can install node modules to a local folder using aliases.

We should bear in mind the [alias name rules](https://www.npmjs.com/package/validate-npm-package-name#naming-rules), although there's nothing surprising here.

I think we probably want to install the runtime modules into a prefixed folder, with a name like `package_x.y.x`. We will need to maintain a package.json (but probably not a package lock) otherwise each new install will result in "unused" packages being removed.

## Bundled adaptors?

A related issue here is: should adaptors be bundled into a single .js file, with all their dependencies included?

A benefit of bundling is that an adaptor can be "installed" simply by extracting the .js and package.json files somewhere. No `npm` install is needed. Managing multiple versions is easy - not least because nested dependencies are included in the file.

On the other hand, the adaptor becomes very bloated, taking up disk space and (potentially) being slower to load.

Note that we can't bundle non-openfn dependencies, so if someone wanted to import lodash, we would have to support an npm install.

Without bundling, we need to decide how strictly to lock dependency versions in the package manifest of the adaptors. Do we allow some patch or even minor level changes to accept fixes? Or do we strictly fix versions to ensure nothing changes?

**Comment by stuartc** [comment]
Will read all of this thoroughly in a bit, but check out npm install aliases. We use this technique on lightning: https://github.com/OpenFn/engine/blob/main/lib/engine/adaptor/repo.ex

Check out the shell command there, we use a combination of aliases with global mode to ensure deps are installed in that packages node_modules.

**Comment by josephjclark** [comment]
Aaah aliases and `npm install --no-save`! I was looking for this option but couldn't seem to find it this morning.

That will really help at a mechanical level, thank you!

**Comment by josephjclark** [comment]
This may not just be a runtime issue: dev-time tooling _might_  also need to lookup an adaptor or module.

The compiler may need to look up a referenced module to look at its imports and validate usage.

Lightning will want to lookup related help and documentation.

But does tooling need to know where adaptors are auto-installed to, or can they just call out to unpkg, or their own cache?

**Comment by josephjclark** [comment]
The CLI now supports auto-install of adaptors, so I'm closing this down.

The short version of the implementation is: the runtime is a aware of a 'repo' has an API to check whether things are installed and install them on demand. Then the CLI will, in come conditions, ask the runtime to actually do the install. The same repo API is used in a couple of places to help looking up modules and type definitions.

The big we haven't done yet is those directives. But that's a bit of a different story...
