### ISSUE TITLE
Bad things happen when an adaptor calls process.exit()

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/kit#520]
## Update

What's actually happening here is that the operation throws, which is caught by the adaptor  in `execute`, which calls `process.exit()`, which kills the worker thread and instantly terminate all messaging back to the parent worker.

## Original Issue

Misusing (at least) the `sql` function in language-postgres can cause a worker crash (rather than a run/attempt crash). That's no good.

This expression isn't proper:

```js
sql('select * from food_hygiene_interview');
```

It's not how the `sql` function is meant to be used. Apparently it requires a function which returns a string (like this: ``) rather than a string itself. I'd expect this to either `fail` (or `crash`) at the run (or attempt) level, but not take down the worker.

Here's what happens when we run it:

```
[R/T] ❯ Starting operation 1
TypeError: sqlQuery is not a function
    at /private/tmp/openfn/worker/repo/node_modules/@openfn/language-postgresql_4.1.8/dist/index.cjs:206:20
    at file:///Users/taylor/build/kit/packages/runtime/dist/index.js:577:26
    at async file:///Users/taylor/build/kit/packages/runtime/dist/index.js:549:20
[SRV] ℹ 3a04be88-9cdb-43b1-8320-baf625a29031 :: attempt:log :: OK
[RTE] ✘ Error: Workerpool Worker terminated Unexpectedly
    exitCode: `1`
    signalCode: `undefined`
    workerpool.script: `/Users/taylor/build/kit/packages/engine-multi/dist/worker/worker.js`
    spawnArgs: `undefined`
    spawnfile: `undefined`
    stdout: `[object Object]`
    stderr: `[object Object]`

    at Worker.<anonymous> (/Users/taylor/build/kit/node_modules/.pnpm/workerpool@6.5.1/node_modules/workerpool/src/WorkerHandler.js:297:13)
    at Worker.emit (node:events:513:28)
    at [kOnExit] (node:internal/worker:279:10)
    at Worker.<computed>.onexit (node:internal/worker:199:20)
[RTE] ❯ Purging workers
[SRV] ℹ 3a04be88-9cdb-43b1-8320-baf625a29031 :: workflow-error :: OK
```

**Comment by josephjclark** [comment]
I thought I was losing my freaking mind here - then I noticed this in the postgres adaptor:
```
export function execute(...operations) {
  const initialState = {
    references: [],
    data: null,
    queries: [],
  };

  return state => {
    return commonExecute(
      createClient,
      connect,
      ...operations,
      disconnect,
      cleanupState
    )({ ...initialState, ...state }).catch(e => {
      console.error(e);
      console.error('Unhandled error in the operations. Exiting process.');
      process.exit(1);
    });
  };
}
```

Basically the adaptor is committing Hara-kiri

**Comment by josephjclark** [comment]
Updated the issue title to reflect the real problem

Note that this should currently be marking the attempt complete with an `exception` reason. The worker thread dies, but the main ws-worker is alive and well.

**Comment by josephjclark** [comment]
Alright, here's the plan:

1) I THINK I can listen for process.exit in the worker thread and send a slightly nicer error out to the main worker
2) Now we can report an error like "killed by process.exit()" or something
3) The reason for the process.exit will be in the logs, but will be unknown to the runtime and lightning (beyond the kill reason and message, which will be quite broad)

Separately, we should go through the adaptors and remove the process.exit calls.

**Comment by josephjclark** [comment]
Just to note a couple of reasons why process.exit is bad in this v2 runtime:

1) The RUNTIME wants to decide when to stop executing a workflow, not the adaptor. When the adaptor process.exits, it denies the runtime the opportunity to execute an on-error edge.
2) If we process.exit then some amount of messages will not get send out of the worker thread and up to Lightning. In my local testing a semi-random set of log lines vanished because the log stream was lost on process.exit
3) The runtime cannot emit or return a rich error message when we process.exit, so we cannot map nice exit reasons or messages from them
