### ISSUE TITLE
Worker hanging/crash on console.log premature string closing 

### ISSUE THREAD

**Issue by jyeshe** [OpenFn/kit#527]
During end to end tests it was detected that a prematurely closed string on console log causes the worker to hang and sometimes crash.

Expression:
```js
fn(state => {
  console.log('and its 'basic auth' form blah');
  return state;
});
```

**Version number** 

ws-worker version `0.2.12`

**Comment by jyeshe** [comment]
To reproduce with Lightning the branch is `console-log-crash`.
On this [commit](https://github.com/OpenFn/Lightning/commit/c8236a873914c9dbff3ec5a9c89e8d54cd57dfd3):
`mix test test/lightning_web/end_to_end_test.exs`

**Comment by josephjclark** [comment]
Thanks @jyeshe !

I've run a couple of quick tests and it looks to me like the Worker correctly returns a crash state. I've got a branch `test-unterminated-string` with tests (which I'll work a bit more on and merge).

I'll have to dig a bit deeper to see what's causing your "hang"

**Comment by jyeshe** [comment]
> Thanks @jyeshe !
> 
> I've run a couple of quick tests and it looks to me like the Worker correctly returns a crash state. I've got a branch `test-unterminated-string` with tests (which I'll work a bit more on and merge).
> 
> I'll have to dig a bit deeper to see what's causing your "hang"

Hi @josephjclark we can skip the hang or freeze as it is a setup on the E2E test. What might need investigation or not, is that sometimes I got a print of nodejs error which I can't reproduce now.
