### ISSUE TITLE
Zombie Workers

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#535]
Issue to track the zombie worker that we've found on  app

> i’m seeing a worker that has… gone quiet? on [app.openfn.org](http://app.openfn.org/) - i’ll start a thread here and keep my notes, but as far as i can tell:
at 9pm gmt last night it sent its last log
kubernetes thinks it’s all happy and good
there’s a queue of work to be done in lightning
but the worker isn’t doing anything or asking for any work
… will update as i learn more

![image](https://github.com/OpenFn/kit/assets/7052509/ca7f1323-aaae-42da-bfd2-e578bb271f49)

**Comment by josephjclark** [comment]
It looks like:

1) Lightning has closed the attempt channel (with good reason I am sure)
2) The worker is waiting to send some kind of message (presumably complete or error)
3) Pheonix is constantly trying to reconnected to the attempt channel - and being refused. So the message won't send and the promise won't resolve.
4) The worker won't close down the tasks because it's waiting for this message to send.

I'm not sure WHY the attempt got lost, but I'm pretty sure that the worker needs to handle this case better.

Probably when a connection to the attempt channel is refused, we need to kill the active attempt and free up the worker.

**Comment by josephjclark** [comment]
We've just seen confirmation that the worker isn't dead or frozen - when lightning is restarted it came back to life and emitted some logs.

**Comment by josephjclark** [comment]
Worker 0.6.0 is now live so I'm hoping this is going to go away now.

**Comment by taylordowns2000** [comment]
We have not seen this since `v0.7.0` - I am closing for now

**Comment by josephjclark** [comment]
Hurrah!
