### ISSUE TITLE
Adopt new terminology (part 2)

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#556]
We need to update the the names of things to match Lightning:

- [ ] consider when we use "jobs" and when we use "steps"
- [x] replace "attempt" with "run"

Notes: 

- I think ExecutionPlan is still OK (although that's just an internal type), and workflow is still fine.
- Should we rename `state` to `input` in the CLI? `-i` is taken. Maybe we can add an `--input` alias.

This applies to all packages in `kit` (CLI, runtime, worker etc).

For each package, we particularly need to check:
* API interfaces
* Any options objects/keys
* All log output

Also note that docs need to change - CLI challenge

**Comment by josephjclark** [comment]
See https://github.com/OpenFn/Lightning/issues/1248 for the changes made in Lightning

**Comment by taylordowns2000** [comment]
part 1 is done via #564

**Comment by taylordowns2000** [comment]
renaming `attempts` to `runs` is done in `0.8.0`,  here we still want to consider jobs, steps, and a few other items in the CLI
