### ISSUE TITLE
worker: send version number when connecting to ws endpoint

### ISSUE THREAD

**Issue by stuartc** [OpenFn/kit#563]
### Details

In order to provide more details about how a step is being run and to give us room to accommodate API changes we should send the version number to Lightning.

### Implementation notes

I think the easiest way (at least from how to get it to Lightning) is to use query parameters. So adding `v: <VERSION>` to the params (`token` is already there).

**Comment by josephjclark** [comment]
@stuartc are you thinking of literally sending the worker version, as per npm, or something more like a contract/spec version, which would just be an increasing integer?

**Comment by josephjclark** [comment]
Spoke to Stu - we'll define a contract spec somewhere in some json or xml or even a spreadsheet, give that contract a version, and send that version number.

But in lieu of a formal document, we'll just call it 1.0 for now

I wonder if the the worker needs to send a two part version, like 1-2, meaning "this is the `1` version of the interface and the `2` version of my implementation of it`. Which gives us wiggle room for bug fixes.

Or I suppose we send contract version and worker version as two values.
