### ISSUE TITLE
Transform projectSpace JSON data for presentation concerns

### ISSUE THREAD

**Issue by elias-ba** [OpenFn/kit#60]
### User story
As a user looking at the workflows diagrams I want to see the title `Untitled` for untitled workflows and a description for `webhook` and / or `cron` workflows.

### Details
For `webhook` the description should be like this `when data is received at https://demo.openfn.org/i/34f843bd-eb87-4833-b32a-905139534d5a` and for `cron` the description should be like `"at 7:34pm every Tuesday"`

**Comment by taylordowns2000** [comment]
@elias-ba , here are the initial diagrams that informed this issue. Your implementation looks 95% there, but the word-wrap isn't quite working as expected and I see an unbalanced box.
![image.png](https://images.zenhubusercontent.com/566ac5e0638e718c995f5356/8ae8bd43-fba0-4bcd-81ab-1b43dd34df60)

**Comment by elias-ba** [comment]
> @elias-ba , here are the initial diagrams that informed this issue. Your implementation looks 95% there, but the word-wrap isn't quite working as expected and I see an unbalanced box.
> 
> Can you make sure this text is spaced, wrapped, and centered properly?
> 
> ## the spec
> ![image.png](https://camo.githubusercontent.com/223665bb75352da1f1b25cdccef5b3ca0b219fa0eb533d91454fcb007753b385/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3536366163356530363338653731386339393566353335362f38616538626434332d666261302d346263642d383161622d316234336464333464663630)
> 
> ## what i'm seeing currently
> ![image.png](https://camo.githubusercontent.com/aa6f0ca4bdf482e84fbf3982b5b6af86639c16834ea5be60acaaeb87f93e3f4e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3536366163356530363338653731386339393566353335362f31306231656235382d316239342d343630372d613736642d323338636663326366373935)

Thanks @taylordowns2000 for the catch. Unfortunately you did add the comment in the issue instead of the PR, then @stuartc missed it and merged the PR which closed this issue. I have create a new issue here #71 to handle this fix.

**Comment by elias-ba** [comment]
@taylordowns2000 see [this PR](https://github.com/OpenFn/kit/pull/72) for fix. Lemme know
