### ISSUE TITLE
Update node versions

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#617]
* Ensure everything works in node 18.19
* Ensure everything works in 20.latest
* Ensure everything works in 21.x

Ideally we should just work across all vaguely modern node versions.

18.19 did something I think to break the loader vm arg, which causes all sorts of problems.

Remember to update the circle config so that CI is also running in the latest version. I'd actually love to run in a matrix with 18,20,22 (at least for a little while)

- Ava tests fail
- the describe-package esbuild script fails

Some constraints on the work:
- The fix should be minimal - ideally this is just a tweak to a couple of config files
- I am hoping that we can continue to test in memory in a single command, rather than compiling tests into .js files and leaving them on disk

**Comment by Akshanshkaushal** [comment]
hi @josephjclark  @christad92  To better understand the codebase, I want to solve this issue. Could you please assign me this?

**Comment by josephjclark** [comment]
So the problem we have is that node 20 changes the way loaders work, which breaks our ava config. This will affect adaptors as well - see https://github.com/OpenFn/adaptors/issues/187

The first problem is that the ts node loader has changed and doesn't work with ava. It works if I use a thing called `tsimp`, but it builds all the test files to disk. Not essential I suppose but it annoys me. Also the docs say it does everything virtually, so that's kinda confusing.

The second problem is some changes about importing folders, which we can't do any more. I suppose we'll just have re-write the affected code, although that could be a big job

**Comment by josephjclark** [comment]
Running ava with workerThreads off (forcing it to use child processes) works fine, at the cost of using more system resources (and so being slower in CI).

What I'm confused at with this is that I don't get import errors for importing folders and stuff, which I do get when using other loaders. Is that just a config thing?

**Comment by josephjclark** [comment]
See also #542
