### ISSUE TITLE
Flaky test in engine

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#761]
This seems to fail in CI occasionally?

`trigger workflow-log for job logs`

In `packges/engine-multi/test/integration.test.ts`

https://app.circleci.com/pipelines/github/OpenFn/kit/2492/workflows/b7831333-7977-4ea9-ab47-dd4fee9a4160/jobs/5678

**Comment by doc-han** [comment]
We need a single long running parent issue for tracking all flaky tests.

**Comment by doc-han** [comment]
Fixed in #832
