### ISSUE TITLE
Update vulnerable packages

### ISSUE THREAD

**Issue by rorymckinley** [OpenFn/kit#763]
This is a bundle issue to cover upgrading issues picked up as a combination `pnpm audit` and dependabot. Each upgrade will be covered by a comment on the issue, covering the reasoning for the upgrade.

**Comment by rorymckinley** [comment]
decode-uri-component: 

This library is only used by devDependencies, so hopefully a safe change to make . The version to be upgraded is `0.2.0` will upgrade to `0.2.2` which has been out for almost 2 years.

**Comment by rorymckinley** [comment]
braces:

"if a malicious user sends "imbalanced braces" as input, the parsing will enter a loop, which will cause the program to start allocating heap memory without freeing it at any moment of the loop" - per https://github.com/advisories/GHSA-grv7-fg5c-xmjg.

`braces` is used by a lot of prod dependencies but, given that we execute what is essentially untrusted code :), it feels prudent to apply the patch version bump. The updated version has been out since May.

**Comment by josephjclark** [comment]
@rorymckinley live-server is only used by an out of date ad unused dev server. We can just remove it and maybe fix the server later (i don't think the demo even needs it).

I'll raise an issue to fix / update the dev demo. You can just remove the `live-server` dependency.

**Comment by rorymckinley** [comment]
Note to self: When submitting the PR, add 'alarming comments' re: the `ws` update as we jumped several minor versions.

**Comment by rorymckinley** [comment]
Updated typesync - bumped up two minor versions as it was depending on ip which does not have a patch for the latest version and no patch on the horizon. `typesync` is a devDependency.

**Comment by rorymckinley** [comment]
postcss: Vulnerability relates to parsing of untrusted CSS - also only a devDependency.

**Comment by rorymckinley** [comment]
micromatch - vulnerable to regex DOS - used in a number of prod dependencies, but only 3 patch version bump needed to get a non-vulnerable version.

**Comment by rorymckinley** [comment]
word-wrap: devDependency  vulnerable to a regex DOS.
