### ISSUE TITLE
CLI: auto-install should ignore  paths

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#77]
This fails today:

`openfn -i -a common=path/to/common`

Basically the autoinstall needs to recognise that a path has been provided for common, so it does't need to acutally autoinstall.

It should always be safe to pass `-i`.

**Comment by stuartc** [comment]
Does it currently pass that path to npm, like install this module over here?

**Comment by josephjclark** [comment]
Basically it's dumb and passes the whole string to npm, so it'll do something like `npm install common=path/to/common`. Which really doesn't help anyone.
