### ISSUE TITLE
describe-package: handle namespaces in export descriptions

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#80]
Some packages export a `beta` namespace.

At the moment, `describe-package` presents the beta namespaced functions as a flat list alongside the main functions - which is a) confusing and b) can lead to duplication (for example, `common` exports two `each` functions).

We basically need to de-flatten the exported list (or flag the namespace).

Probably we need to utilise the new `package` structure which is returned and `namespaces` to the `functions` properties, or something.

**Comment by taylordowns2000** [comment]
@josephjclark , @stuartc , when i run stuff that requires `beta.each` on the new CLI it's not working as expected. Is this still an issue or is there a different way to access namespaced functions like this?

<img width="1455" alt="image" src="https://github.com/OpenFn/kit/assets/8732845/3f8b4f77-16d0-4a62-85a5-d297d9c27ef8">

**Comment by josephjclark** [comment]
This is actually a duplicate of #238, closing it down. 

A workaround will shortly be released.
