### ISSUE TITLE
Logger: Removed configuration from final state

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#827]
I hate this line:
```
Removed configuration from final state
```

It's a reasonably important line. It runs at the end of every step.

But when there's an error, it tends to appear before the error. Or it's the last  log line we receive.

And it looks  like it's the cause of a fail, rather than the effect of a step being completed.

I'm not really sure what to do about this. Logging to debug and adding a debug filter would help.

**Comment by doc-han** [comment]
1. Unable to reproduce a situation where that line is logged after an error. 
2. I get beautiful logs on CLI that helps in knowing which part of the logs shows the error.

<div align="center">
  <img src="https://github.com/user-attachments/assets/a49ef7d1-ea00-42d3-b5ba-872f3b51fe40" alt="some code" width="50%" />
</div>
3. Maybe it's just a UI thing where lightening logs needs to also be colorful?
<div align="center">
  <img src="https://github.com/user-attachments/assets/7b6fce81-6818-4c57-8a10-d4e0335d094b" alt="some code" width="50%" />
</div>

**Comment by josephjclark** [comment]
I think a bit of context would go a long way here.

Maybe if the logs looked more like this (I'm just sketching, and on a mobile device too)

```
(Debug) Step complete with status: complete
(Debug) Cleaning up state. Removing keys: configuration 
```
In such a long, the key removal always comes after some kind of orderly job closure, so it makes a bit more sense about what is happening

**Comment by josephjclark** [comment]
Or I suppose just having the key removal line AFTER the job failed line would go a long way

**Comment by doc-han** [comment]
Ohkay, that makes sense.
