### ISSUE TITLE
describe-package: export/from seems to export symbols as "unknown"

### ISSUE THREAD

**Issue by josephjclark** [OpenFn/kit#86]
Here's a weird thing.

I was just looking at the docs for `primero` and `describe-package` isn't reporting the exports from common.

In `Adaptor.js` we do this:

```
export {
  alterState,
 . ..
} from '@openfn/language-common';
```

Looking at the output of `getSymbols()`, typescript seems to recognise the names of all these exports as `unknown`. It doesn't seem to pull out any useful information at all.

I wonder if that's because there's no definition of `common` available in the TS project. In fact that's probably it: even if it was able to scrape the names of these exports, it wouldn't be able to report any type information.

So, `describe-package` may have to somehow pull the definitions of any dependencies into the Project in order to properly report types. Because this doesn't just apply to language adaptors - `http` exports `axios`, for example...

**Comment by stuartc** [comment]
Blerg, this smells like 'fetch them yourself' or do a dts rollup again right?

**Comment by josephjclark** [comment]
Yup.

A rollup would have to include exported aliases - which is the same problem in one files or a bundle. Either way it puts the onus on the adaptors build. Also, looking forward 5000 years, it means we can only document stuff built in a certain way.

That leaves us with fetching all the definitions ourselves, which isn't particularly appealing either. Especially from the client side. It means we have to parse the definitions for all imports in the DTSes, recursively, and load them all.

When we move docgen server-side, this becomes a bit more appealing. The project build is still heavyweight but at least we can cache effectively, which will really help. I don't know how that'll work architecturally with Lightning, and I guess `describe-package` will need to decide how opinionated it is about where it runs (should it start assuming its a server side component? Should it cache itself?). It's a whole thing.

I think a good compromise to get us moving quickly would be to always load `common` into the `describe-package` Project. One more file load won't kill us at this stage and it'll fix most, if not all, of the cases.
